set(CMAKE_SYSTEM_NAME               Generic)
set(CMAKE_SYSTEM_PROCESSOR          arm)

set(CMAKE_C_STANDARD 				11)
set(CMAKE_CXX_STANDARD 				14)
set(CMAKE_C_STANDARD_REQUIRED 		ON)
set(CMAKE_C_EXTENSIONS 				ON)
set(CMAKE_C_COMPILER_FORCED 		TRUE)
set(CMAKE_CXX_COMPILER_FORCED 		TRUE)
set(CMAKE_C_COMPILER_ID 			GNU)
set(CMAKE_CXX_COMPILER_ID 			GNU)
set(CMAKE_EXPORT_COMPILE_COMMANDS 	TRUE)

set(TOOLCHAIN_PREFIX                arm-none-eabi-)
set(CMAKE_C_COMPILER                ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_ASM_COMPILER              ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER              ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_LINKER                    ${TOOLCHAIN_PREFIX}g++)
set(CMAKE_OBJCOPY                   ${TOOLCHAIN_PREFIX}objcopy)
set(CMAKE_SIZE                      ${TOOLCHAIN_PREFIX}size)

set(CMAKE_EXECUTABLE_SUFFIX_ASM     ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_C       ".elf")
set(CMAKE_EXECUTABLE_SUFFIX_CXX     ".elf")




